version: "3"

services:
  server:
    build: './server/'
    ports:
      - "5000:5000"
    volumes:
      - './server/:/server'
  quiz-app:
    build: './quiz-app'
    ports:
      - "80:4200"
    volumes:
      - './quiz-app:/quiz-app'
      - '/quiz-app/node_modules'